defaults:
  - _self_
  - dataset: "niceslam_replica"
  - mapping: "semantic_voxel_map"
  - encoder: "naradio"
  - vis: "rerun" # Set to null to disable
  - messaging_service: null # Set to null to disable
  - feat_compressor: null # Set to null to disable
  - extras

# Disable logging to files
hydra:
  output_subdir: null
  run:
    dir: .

# How many frames should be batched before processing.
batch_size: 1

# Imposing a depth limit on the data such that to test limited depth scenarios
# Set to a negative number to not use a limit
depth_limit: -1

# Which pytorch interpolation mode for rgb and feature interpolation 
# (Depth and Segmentation always use nearest-exact)
interp_mode: bilinear

querying:

  # If not set to null then text querying is enabled. If query is set to `prompts` 
  # then every line from the query file is considered as a prompt. If set to 
  # labels then every line will be considered as a label that will be injected 
  # into multiple prompt templates and averaged out to get the text embedding.
  text_query_mode: "labels" # [null, "labels", "prompts"]

  # Whether to query in compressed feature space or decompress first. Only used
  # if feat_compressor was used.
  compressed: False

  # A query file used to initialize the list of queries will be used to query
  # the map periodically and visualizing the results.
  # The query file can be a .txt or .json file.
  # .txt: each line represents a query. If the query is a locally existing file
  # name, then it attempts to load that file as an image query. If no file 
  # exists, the query is assumed to be a text query.
  # .json: A dictionary where the query is the key and the value is a hex
  # color such that the query is colorized using that in the visualization.
  query_file: '/workspace/RayFronts/test.txt'

  # Whether softmax probability is computed across queries or not.
  # If you want results to be independent of other queries set this to false.
  # Image queries are seperated from text queries. i.e the softmax is computed
  # separately for the text query group and the image query group.
  compute_prob: False

  # How often should the mapping server update query results in the map.
  period: 10

seed: 17
