defaults:
  - default
  - override mapping: semantic_ray_frontiers_map
  - override encoder: radio
  - _self_

compile: False
amp: True
depth_limit: 20.0

encoder:
  model_version: radio_v2.5-b
  lang_model: siglip

dataset:
  rgb_resolution: [480, 304] #[480, 304]
  depth_resolution: [480, 304] #[480, 304]

mapping:
  vox_size: 0.50
  max_pts_per_frame: 300 #-1
  max_empty_pts_per_frame: 20000
  max_rays_per_frame: 10 #500
  fronti_subsampling: 8
  fronti_subsampling_min_fronti: 20
  ray_tracing: False
  vox_accum_period: 2 #4
  ray_accum_period: 2 #4
  ray_accum_phase: 1 #2
  ray_erosion: 0
  global_encoding: True



